spring.application.name=control-accesos-api
spring.profiles.active=dev
server.port=8080
jwt.secret=${JWT_SECRET:YWFhYmJiY2NjZGRkZWVlZmZmMTIzNDU2Nzg5MGFiY2RlZjEyMzQ1Njc4OTA=}
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:1209600000}
